name: Maven CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: 
        distribution: 'temurin'
        java-version: '21'

    - name: Testing the code
      run: mvn clean install

  test: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: 
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean test

  sonar_upload:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: 
        distribution: 'temurin'
        java-version: '21'

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AFTABSHIAKH786_github_action-practice -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      
